config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  resources :marks
  resources :subjects
  resources :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :students
end

app/models/mark.rb
class Mark < ApplicationRecord
	belongs_to :student
	belongs_to :subject
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :subjects
	belongs_to :group
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
	@groups = Group.all
	end

	def show
    @group = Group.joins("INNER JOIN students ON students.id = groups.student_id")
    end

	def new
		@group = Group.new
	end

	def create
 	@group = Group.new(group_params)
  	@group.save
  	redirect_to @group	
  	end

	private

	def group_params
    	params.require(:group).permit(:name, :student_id)
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
	@students = Student.all
	end

	def show
    @student = Student.find(params[:id])
    end

	def new
		@student = Student.new
	end

	def create
 	@student = Student.new(student_params)
  	@student.save
  	redirect_to @student	
  	end

	private

	def student_params
    	params.require(:student).permit(:name, :email)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/groups/index.html.erb
<h1>Groups</h1>

app/views/groups/new.html.erb
<%= form_with scope: :group, url: groups_path, local: true do |form| %>  <p>
    <%= form.label :Group %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :Student %><br>
    <%= collection_select(:group, :student_id, Student.all, :id, :name) %>  </p>
  <p>
   <%= form.submit %>
  </p>
<% end %>

app/views/groups/show.html.erb
<p>
  <strong> Group Name:</strong>
  <%= @group.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @group.student.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>Students</h1>

app/views/students/new.html.erb
<%= form_with scope: :student, url: students_path, local: true do |form| %>  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :Email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

app/views/subjects/show.html.erb
show.html.er